name: addons-release
on:
  push:
    branches:
      - master

env:
  MAX_PY_VERSION: "3.11"
  MIN_PY_VERSION: "3.9"
jobs:
  release-wheel:
    name: Test and build release wheels
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - id: author-date
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script:
            "const commit_details = await github.git.getCommit({owner: context.repo.owner,
            repo: context.repo.repo, commit_sha: context.sha});

            return commit_details.data.author.date

            "
      - if: matrix.tf-version != '2.15.0'
        run: echo "SKIP_CUSTOM_OP_TESTS=--skip-custom-ops" >> $GITHUB_ENV
        shell: bash
      - id: measurement-3
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - if: github.event_name == 'push'
        run: echo "NIGHTLY_FLAG=--nightly" >> $GITHUB_ENV
        shell: bash
      - id: measurement-5
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}
      - if: matrix.os != 'ubuntu-20.04'
        name: Setup Bazel
        run: bash tools/install_deps/install_bazelisk.sh ./
      - id: measurement-9
        name: Record Measurement After Setup Bazel
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Setup Bazel
          task: get-measurement
      - env:
          CPU: ${{ matrix.cpu }}
          NIGHTLY_TIME: ${{ steps.author-date.outputs.result }}
          OS: ${{ runner.os }}
          PY_VERSION: ${{ matrix.py-version }}
          TF_VERSION: ${{ matrix.tf-version }}
        name: Build wheels
        run: bash .github/workflows/make_wheel_${OS}_${CPU}.sh
        shell: bash
      - id: measurement-11
        name: Record Measurement After Build wheels
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build wheels
          task: get-measurement
      - uses: actions/upload-artifact@v1
        with:
          name:
            ${{ runner.os }}-${{ matrix.py-version }}-tf${{ matrix.tf-version
            }}-${{ matrix.cpu }}-wheel
          path: wheelhouse
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        cpu:
          - x86
        include:
          - cpu: arm64
            os: macos-12
            py-version: "3.9"
            tf-version: 2.15.0
          - cpu: arm64
            os: macos-12
            py-version: "3.10"
            tf-version: 2.15.0
          - cpu: arm64
            os: macos-12
            py-version: "3.11"
            tf-version: 2.15.0
        os:
          - macos-12
          - ubuntu-20.04
        py-version:
          - "3.9"
          - "3.10"
          - "3.11"
        tf-version:
          - 2.13.1
          - 2.14.0
          - 2.15.0
  test-with-bazel:
    name: Test with bazel
    runs-on: ubuntu-20.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.MIN_PY_VERSION }}
      - name: Build wheels
        run:
          "pip install --default-timeout=1000 -r tools/install_deps/pytest.txt
          -r tools/install_deps/tensorflow-cpu.txt -r requirements.txt

          bash tools/install_deps/install_bazelisk.sh ./

          python configure.py

          bazel test -k --test_timeout 300,450,1200,3600 --test_output=errors //tensorflow_addons/...

          "
      - id: measurement-4
        name: Record Measurement After Build wheels
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build wheels
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  upload-dev-container:
    env:
      PY_VERSION: "3.9"
    if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
    name: Upload dev container to DockerHub
    needs:
      - release-wheel
      - test-with-bazel
    runs-on: ubuntu-20.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v2
      - run: "set -e -x

          echo ${{ secrets.DOCKER_PW }} | docker login --username ${{ secrets.DOCKER_USER
          }} --password-stdin

          bash .github/workflows/github_build_dev_container.sh

          docker push tfaddons/dev_container:latest-gpu

          "
      - id: measurement-3
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
  upload-wheels:
    if:
      (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name
      == 'release'
    name: Publish wheels to PyPi
    needs:
      - release-wheel
      - test-with-bazel
    runs-on: ubuntu-20.04
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/download-artifact@v1
        with:
          name:
            ${{ matrix.os }}-${{ matrix.py-version }}-tf${{ matrix.tf-version
            }}-${{ matrix.cpu }}-wheel
          path: ./dist
      - run: "set -e -x

          ls -la dist/

          sha256sum dist/*.whl

          "
      - id: measurement-3
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          password: ${{ secrets.pypi_token }}
          user: __token__
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        cpu:
          - x86
        include:
          - cpu: arm64
            os: macOS
            py-version: "3.9"
            tf-version: 2.15.0
          - cpu: arm64
            os: macOS
            py-version: "3.10"
            tf-version: 2.15.0
          - cpu: arm64
            os: macOS
            py-version: "3.11"
            tf-version: 2.15.0
        os:
          - macOS
          - Linux
        py-version:
          - "3.9"
          - "3.10"
          - "3.11"
        tf-version:
          - 2.15.0
permissions:
  contents: read
